// @twt/tokens — semantic CSS generator (Story 1.17, AC2 / UX §6 FM-4).
//
// `renderThemeCss()` deterministically renders the TS token source (src/tokens.ts)
// into a Tailwind v4 `@theme` CSS-variable block. Tailwind v4 is configured
// CSS-FIRST (there is no tailwind.config.* in the repo) — web consumers `@import`
// the generated artifact, so the generator emits an `@theme {}` block, not a JS
// config object.
//
// FM-4 token-sync discipline: the TS source is canonical; the committed
// src/theme.css is the compiled output. scripts/check-theme-determinism.ts
// re-renders and byte-compares, failing the build on drift (the OpenAPI-determinism
// precedent: "regenerate and assert identical").
//
// Namespacing: Tailwind v4 generates utilities from recognized `@theme` namespaces,
// so colors emit under `--color-*` (→ `bg-*`/`text-*`/`border-*`) and faces under
// `--font-*` (→ `font-*`). The UX-DR9 spacing/border tokens are a DISCRETE NAMED set
// consumed via `var(--space-row)` / `var(--border-rule)` (not Tailwind's numeric
// `--spacing` scale), so their committed names are emitted VERBATIM as `--space-*` /
// `--border-*`. NO shadow variables are emitted (FM-3: hairline-based separation).

import { border, color, font, space } from './tokens.js';
import type { TokenGroup } from './tokens.js';

const GENERATED_HEADER =
  '/* GENERATED by @twt/tokens (src/theme.ts) from the TS token source (src/tokens.ts).\n' +
  ' * DO NOT EDIT BY HAND. Regenerate: `pnpm --filter @twt/tokens tokens:generate-theme`.\n' +
  ' * The FM-4 sync check (pnpm --filter @twt/tokens tokens:check-theme-determinism)\n' +
  ' * fails the build if this file drifts from the source. */';

/** Render one labelled group of `<prefix><name>: <value>;` declarations, in declaration order. */
function renderGroup(label: string, group: TokenGroup, prefix: string): string {
  const lines = Object.entries(group).map(([name, value]) => `  ${prefix}${name}: ${value};`);
  return [`  /* ${label} */`, ...lines].join('\n');
}

/**
 * Render the full Tailwind v4 `@theme` artifact. PURE + DETERMINISTIC: same source →
 * byte-identical output (object key order is insertion order; no Date/random/env).
 */
export function renderThemeCss(): string {
  const groups = [
    renderGroup(
      'Color — semantic role aliases (UX §8) + general aliases + the FIRM admin status palette',
      color,
      '--color-',
    ),
    renderGroup(
      'Typography — UX-DR9 type-role faces (FM-2 substitution policy in README)',
      font,
      '--font-',
    ),
    renderGroup('Spacing — UX-DR9 named scale (placeholder px until P0-2)', space, '--'),
    renderGroup('Borders — hairline-based separation, NO shadows (FM-3)', border, '--'),
  ];
  return `${GENERATED_HEADER}\n@theme {\n${groups.join('\n\n')}\n}\n`;
}
