// @twt/tokens — hand-rolled semantic design-token registry (Story 1.17, AC1).
//
// The SINGLE token source (UX spec §6 "Design System Choice", L651/750: the package
// is @twt/tokens, v1 is a hand-rolled TS module — NOT Style Dictionary; migration
// trigger = second-Pariwar provisioning OR first non-TS consumer, see README).
//
// Framework-neutral by contract (architecture §4.1): no web-only or RN-only imports,
// so both the Tailwind v4 `@theme` artifact (web, generated by src/theme.ts) and a
// future Tamagui theme (native, FM-1) can consume the same constants.
//
// FM-14 token-governance discipline (UX spec L788-793):
//   #1 every token name expresses a SEMANTIC ROLE, never an arbitrary index
//      (no `color-1`/`color-2`) — enforced by tests/tokens.test.ts.
//   #3 every token group carries a brief purpose / consumer comment (below).
//   (#2 "no magic numbers in component code" is the CI-lintable rule enforced by the
//      scripts/microcopy/ gate; #4 deprecate-before-remove governs future removals.)
//
// Values policy: per-member-surface COLOR / SPACING / BORDER pixel values are P0-2
// prototype validation TARGETS, not v1 commitments (UX spec FM-5) — what v1 commits
// is the SEMANTIC STRUCTURE + the AA-contrast discipline + the names. The two
// exceptions are FIRM: the admin status palette (subsumed from the DD-1 inline
// `apps/admin/src/styles.css` @theme, §4.10 AA-contrast banners — carried over
// byte-for-byte, no visual regression) and the 1px hairline primitives.

/** A token group maps a semantic role name → its CSS value. */
export type TokenGroup = Readonly<Record<string, string>>;

// ─────────────────────────────────────────────────────────────────────────────
// Color — consumed by every surface for ink / paper / rules / stamps / status.
// Semantic role aliases (UX §8 L1092) + general aliases. Names only express ROLE
// (FM-14 #1). PLACEHOLDER values carry AA-contrast intent; they firm up at P0-2.
// ─────────────────────────────────────────────────────────────────────────────
export const color = {
  // §8 semantic role aliases (member-surface palette; PLACEHOLDER until P0-2/FM-5).
  'ink-primary': '#1a1a1a', // primary text ink on paper
  'surface-base': '#fbfbf8', // page "paper" base
  'surface-accent': '#f1efe8', // raised/inset panel paper
  'rule-hairline': '#d8d4c8', // 1px separating rule (FM-3 hairline discipline)
  'rule-heavy': '#3a3733', // emphatic divider rule
  'stamp-mudra': '#a23b2e', // warm-red ceremonial stamp / seal accent
  'status-pending': '#8a6d00', // pending (yellow family, AA on paper)
  'status-confirmed': '#0f5132', // confirmed (green family, AA on paper)
  'status-mismatch': '#8a4b1f', // mismatch (warm-umber family, AA on paper)
  'status-grey-takeover': '#6b6b6b', // grey takeover / disabled-authority state
  'status-held': '#4b4f66', // held — trustee-frozen / under-review (Story 9.6): a subdued slate-indigo
  //                            neutral, distinct from status-grey-takeover (grey = "on record", held =
  //                            "under review"); dignified not alarming; AA 7.76:1 on surface-base.

  // General aliases (semantic shorthands re-using the role palette above).
  bg: '#fbfbf8', // app background
  surface: '#ffffff', // card / sheet surface
  text: '#1a1a1a', // default text ink
  accent: '#a23b2e', // accent (= stamp-mudra family)
  danger: '#842029', // destructive / error
  success: '#0f5132', // success / confirmed
  warning: '#8a6d00', // caution / pending

  // Admin status palette — FIRM. Subsumed from apps/admin/src/styles.css @theme
  // (Story 1.11b DD-1 / D4-1.11b extraction trigger). AA-contrast pairs for the
  // §4.10 integrity banners; carried over EXACTLY (no visual/contrast regression).
  'status-ok-bg': '#e7f6ec',
  'status-ok-fg': '#0f5132',
  'status-ok-border': '#198754',
  'status-fail-bg': '#fdecec',
  'status-fail-fg': '#842029',
  'status-fail-border': '#dc3545',
  'status-muted-bg': '#f3f4f6',
  'status-muted-fg': '#374151',
} as const satisfies TokenGroup;

// ─────────────────────────────────────────────────────────────────────────────
// Typography — the five UX-DR9 type-role tokens (EXACT names, FM-14 #1). Each maps
// to its canonical Devanagari face with a documented Latin pairing. The per-role
// per-device fallback LADDER is a P0-2 output (FM-2) — this commits the face + a
// substitution POLICY (see README), not a frozen ladder. Type-scale sizes: P0-2.
// ─────────────────────────────────────────────────────────────────────────────
export const font = {
  'display-name': "'Tiro Devanagari Hindi', 'Georgia', serif", // member/Pariwar display name
  'display-parichay': "'Tiro Devanagari Hindi', 'Georgia', serif", // parichay (intro) display
  'body-ledger': "'Noto Sans Devanagari', 'Inter', system-ui, sans-serif", // ledger / body copy
  'numeric-tabular': "'IBM Plex Mono Devanagari', 'IBM Plex Mono', ui-monospace, monospace", // tabular figures (amounts/dates)
  'caption-stamp': "'Noto Sans Devanagari', 'Inter', system-ui, sans-serif", // captions / stamp labels
} as const satisfies TokenGroup;

// ─────────────────────────────────────────────────────────────────────────────
// Spacing — the four UX-DR9 NAMED tokens (a discrete named set, NOT a free numeric
// scale). The committed contract is the NAMES; pixel values are PLACEHOLDER until
// the P0-2 prototype commits them. Consumed via `var(--space-row)` etc.
// ─────────────────────────────────────────────────────────────────────────────
export const space = {
  'space-hairline': '1px', // hairline gap (firm 1px primitive)
  'space-row': '8px', // intra-row rhythm (placeholder)
  'space-block': '16px', // block separation (placeholder)
  'space-page-gutter': '24px', // page gutter (placeholder)
} as const satisfies TokenGroup;

// ─────────────────────────────────────────────────────────────────────────────
// Borders — separation is HAIRLINE-based (FM-3). SHADOWS DO NOT EXIST as tokens:
// no shadow token here, and src/theme.ts emits no shadow utility. Border widths are
// PLACEHOLDER until P0-2. Consumed via `var(--border-rule)` etc.
// ─────────────────────────────────────────────────────────────────────────────
export const border = {
  'border-hairline': '1px', // hairline rule (firm 1px primitive)
  'border-rule': '2px', // standard rule (placeholder)
  'border-double-rule': '3px', // double / emphatic rule (placeholder)
  'border-funeral-frame': '4px', // Shradhanjali memorial frame (placeholder)
} as const satisfies TokenGroup;

/** The whole registry, grouped — the single import surface for consumers + the generator. */
export const tokens = { color, font, space, border } as const;
