// `helpdesk_routing_policy_versions` table — Story 10.1 (Task 2; AC2).
//
// The versioned, per-Pariwar routing-policy registry — the Story 2.3 `clause_versions`
// immutability posture applied to routing rules. A policy update INSERTs a NEW version row;
// prior rows are NEVER mutated except the `superseded_by_version` forward-pointer.
//
// ── This table holds per-Pariwar OVERRIDES only; the default v1 is CODE DATA ───────────────
// AR-46: "the default policy applies when a Pariwar has no override." Following the
// `roles.ts` `defaultRoleBundles` / `pool_names` opt-out precedent the Dev Notes cite, the
// DEFAULT routing policy v1 is seeded as a CODE CONSTANT (`DEFAULT_ROUTING_POLICY` in
// helpdesk/registry.ts), NOT a table row — so this table needs no cross-tenant sentinel row
// and no cross-readable RLS carve-out (plain tenant isolation). `routingPolicyVersionInForce`
// returns a Pariwar's latest effective override, else the code default.
//
// ── The version PIN is (pariwar_id, version) — no separate version-id column ────────────────
// A ticket stores ONLY `routing_policy_version` (int, the FR-8 non-retroactivity snapshot).
// Per-Pariwar override versions start at 2 (the default owns version 1, a code constant, never
// a row here — see helpdesk/registry.ts), so `(pariwar_id, version)` unambiguously identifies
// the exact document for replay WITHOUT an extra `routing_policy_version_id` column.
//
// JSONB inner keys are snake_case (the clause_versions convention) — matching the
// `@twt/contracts/helpdesk` `RoutingPolicyDocument` wire shape exactly (sync-guard test).

import { index, integer, jsonb, pgTable, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

import type { HelpdeskRoutingPolicyVersionId, PariwarId, UserId } from '../ids/index.js';
import type { HelpdeskCategory } from './helpdesk_tickets.js';

/** One routing rule (JSONB, snake_case — mirrors the contract `RoutingRule`). `sub_category:
 *  null` matches ANY subcategory in the category. SLA budgets are DATA on the rule. */
export interface RoutingRuleJson {
  category: HelpdeskCategory;
  sub_category: string | null;
  target_role: string;
  target_scope_dimension: string;
  sla_first_response_hours: number;
  sla_resolution_business_days: number;
}

/** A routing-policy document (JSONB) — the version pin + the EXPLICITLY-ORDERED first-match
 *  rule list. Mirrors the contract `RoutingPolicyDocument`. */
export interface RoutingPolicyDocumentJson {
  version: number;
  rules: RoutingRuleJson[];
}

export const helpdeskRoutingPolicyVersions = pgTable(
  'helpdesk_routing_policy_versions',
  {
    // Per-row address (UUID). DB-defaulted, or PRE-GENERATED by an audited write (the Story 2.4
    // pattern). Branded `HelpdeskRoutingPolicyVersionId`. The exact-document replay pin.
    id: uuid('id').defaultRandom().primaryKey().$type<HelpdeskRoutingPolicyVersionId>(),

    // Tenant key + RLS predicate column. Branded `PariwarId`. Overrides only — the default is
    // code data, never a row here.
    pariwarId: uuid('pariwar_id').notNull().$type<PariwarId>(),

    // Monotonic per pariwar_id, starting at 1 (this Pariwar's OWN override sequence; independent
    // of the code default's version 1). The (pariwar_id, version) unique index is the guard.
    version: integer('version').notNull(),

    // The version's effective instant — `routingPolicyVersionInForce(pariwarId, at)` resolves the
    // latest row with effective_at <= at (DB-authoritative point-in-time).
    effectiveAt: timestamp('effective_at', { withTimezone: true, mode: 'date' }).notNull(),

    // The ordered rule list (opaque JSONB — the resolver interprets it, the table stores it).
    policyDocument: jsonb('policy_document').notNull().$type<RoutingPolicyDocumentJson>(),

    // WHO authored this version (NON-PII controlled-staff attribution); null = system/seed.
    authoredByActor: uuid('authored_by_actor').$type<UserId>(),

    // The audit line for the write (AC2 audit-logged on write). Nullable — a plain reference.
    auditId: uuid('audit_id'),

    // The immutability forward-pointer (the ONLY legitimately-mutable column, clause_versions
    // twin): set on the PRIOR row when a new version is created. Points to the successor's
    // `version` int (self-referential within the same pariwar_id). Null = this is the latest.
    supersededByVersion: integer('superseded_by_version'),

    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  },
  (t) => [
    // The per-Pariwar monotonic version guard (a duplicate version is a 23505, never an update).
    uniqueIndex('helpdesk_routing_policy_versions_pariwar_version_uq').on(t.pariwarId, t.version),
    // In-force resolution scans per (tenant, effective_at).
    index('helpdesk_routing_policy_versions_pariwar_effective_idx').on(t.pariwarId, t.effectiveAt),
  ],
);

export type HelpdeskRoutingPolicyVersionRow = typeof helpdeskRoutingPolicyVersions.$inferSelect;
export type HelpdeskRoutingPolicyVersionInsert = typeof helpdeskRoutingPolicyVersions.$inferInsert;
