-- Migration 0095 — pariwar_custom_field_definitions (Story 10.12, Task 2; AC1/AC3).
--
-- The per-Pariwar, per-host-entity, APPEND-ONLY VERSIONED registry of tenant-authored custom-field
-- definitions. Mirrors 0084's routing-policy half (versioned-immutable rows + composite self-FK +
-- append-only trigger) and 0088's CHECK-mirror doctrine.
--
-- ⚠ DO NOT REGENERATE with `db:generate` (the discipline from 0021 onward): the drizzle snapshot
-- baseline is frozen at 0020_snapshot.json, so a regenerate diffs CURRENT schema against 0020, wrongly
-- re-emits applied migrations and can raise 42P07. HAND-AUTHORED, carrying ONLY this story's DDL. No
-- snapshot emitted.
--
-- ⚠ DO NOT EDIT THIS FILE ONCE APPLIED. drizzle-kit skips an already-applied migration by journal
-- `when` (NOT by SQL hash), so an in-place edit silently never runs — the change would exist in the
-- file and nowhere else, which is worse than not making it. Add a new migration instead.
--
-- The roles (twt_app / twt_service) already exist from migration 0002 — no CREATE ROLE.
--
-- Hand-supplements (relative to what drizzle would emit):
--   1. GRANT SELECT, INSERT, UPDATE to twt_app. NOT DELETE — retirement is a VERSION (a new row with
--      retired_at set), never a row removal. A deleted definition makes every value stored under it
--      uninterpretable, which is data loss dressed as tidying.
--   2. ENABLE + FORCE ROW LEVEL SECURITY (FORCE applies even to the non-superuser table owner).
--   3. The three tenant-isolation policies, from policies/pariwar-custom-field-definitions-rls.ts.
--   4. The append-only BEFORE UPDATE trigger (0084 hand-supplement #4 is the template): the SOLE
--      legitimately-mutable column on an existing row is superseded_by_version.
--   5. The composite self-FK on the forward-pointer. ⚠ It references the FULL TUPLE
--      (pariwar_id, host_entity, field_key, superseded_by_version) → (…, version). A bare
--      version→version reference would not even be creatable: `version` alone is NOT unique here, and
--      the only unique key is the four-column pin below.
--   6. ⭐ THE FROZEN-GOVERNANCE CHECK — layer 2 of AC3. See its own comment block.
--
-- ⚠ NOTE WHAT IS ABSENT: no `current_state` write-rejection trigger and no state-invariant gate. This
-- is NOT a sixth event-derived-state primitive (the 10.8 Decision-3 split): nothing outside the admin
-- write path ever moves a definition — an admin publishes a version, and the version IS the record.

CREATE TABLE "pariwar_custom_field_definitions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"pariwar_id" uuid NOT NULL,
	"host_entity" text NOT NULL,
	"field_key" text NOT NULL,
	"version" integer NOT NULL,
	"definition" jsonb NOT NULL,
	"effective_at" timestamp with time zone NOT NULL,
	"retired_at" timestamp with time zone,
	"authored_by_actor" uuid,
	"actor_display" text,
	"audit_id" uuid,
	"superseded_by_version" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- (1) Table privileges. SELECT/INSERT/UPDATE only — see the header for why never DELETE.
GRANT SELECT, INSERT, UPDATE ON "pariwar_custom_field_definitions" TO twt_app;--> statement-breakpoint
-- (2) RLS on, then FORCEd.
ALTER TABLE "pariwar_custom_field_definitions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pariwar_custom_field_definitions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
-- ⭐ THE VERSION PIN. A duplicate is a 23505 → CustomFieldDefinitionConflictError → 409, never a
-- silent overwrite. Also the FK target for the forward-pointer below, which is why it must be the
-- full four-column tuple.
CREATE UNIQUE INDEX "pariwar_custom_field_definitions_pariwar_host_key_version_uq" ON "pariwar_custom_field_definitions" USING btree ("pariwar_id","host_entity","field_key","version");--> statement-breakpoint
-- In-force resolution scans per (tenant, host, instant).
CREATE INDEX "pariwar_custom_field_definitions_pariwar_host_effective_idx" ON "pariwar_custom_field_definitions" USING btree ("pariwar_id","host_entity","effective_at");--> statement-breakpoint
-- (5) The supersession forward-pointer can only ever point at a version that really exists for the
-- SAME (pariwar, host, field). Safe given the write order in registry.ts publishDefinitionVersion:
-- the new version row is INSERTed FIRST, THEN the prior row's superseded_by_version is UPDATEd to
-- point at it — the referenced row already exists.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_superseded_by_fk"
  FOREIGN KEY ("pariwar_id", "host_entity", "field_key", "superseded_by_version")
  REFERENCES "pariwar_custom_field_definitions" ("pariwar_id", "host_entity", "field_key", "version");--> statement-breakpoint

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- ⭐ (6) LAYER 2 OF THE GOVERNANCE FENCE (Story 10.12 AC3) — the DB mirror.
--
-- Migration 0088's doctrine, verbatim: "an app-layer rule with no DB mirror is a rule that holds only
-- for the callers who happen to go through the app layer."
--
-- The app-layer fence (packages/domain/src/custom-fields/frozen-governance.ts) is richer than this:
-- it carries thirteen pattern families and normalizes `-`, `.` and whitespace to `_` before matching.
-- This CHECK deliberately does NOT try to reproduce all of that — a CHECK deep enough to encode the
-- whole denylist would be a rule engine in DDL, and one that drifted from the TS would be worse than
-- none. What it MUST cover, and does, is the `payout_destination*` family: the FR-100 non-add
-- artifact (architecture §1.13 Hook 2), the one epics.md:3605 names by example, and the one whose
-- absence would be a forward-compat breach rather than an untidy field name.
--
-- The normalization is applied inside the constraint (lower + translate) so `Payout-Destinations` and
-- `payout.destination` are caught here too, not only in TS. A fence a tenant steps over by changing a
-- hyphen is decoration.
--
-- ⚠ WHY THE EPIC'S OWN CITATION COULD NOT DO THIS JOB. epics.md:3605 says a `payout_destinations`
-- field "is rejected by Story 1.16c CI gate". Story 1.16c is `schema-diff`, an invariant scan of
-- COMMITTED REPO STATE — migrations, route literals, Zod exports. A custom field is a key inside a
-- JSONB payload authored at runtime into a database row; `pnpm schema:check` would pass, green and
-- useless, while a Pariwar admin created the field. This constraint, plus the runtime fence, plus
-- `scripts/custom-field-governance/`, are what that citation assumed already existed.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_frozen_key_ck"
  CHECK (
    translate(lower("field_key"), '-. ', '___') NOT LIKE 'payout\_destination%'
    AND translate(lower("definition" ->> 'field_key'), '-. ', '___') NOT LIKE 'payout\_destination%'
  );--> statement-breakpoint

-- (7a) Versions start at 1. Unlike feature_flag_versions (whose CHECK is `>= 2`, because a code
-- constant owns version 1 there), custom fields have NO code-resident default: a Pariwar with zero
-- rows simply has no custom fields (story D2). So 1 is the real first version and 0/negative is
-- meaningless.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_version_min_ck" CHECK ("version" >= 1);--> statement-breakpoint

-- (7b) The supersession forward-pointer must point FORWARD. Kills the self-reference and
-- backward-reference cases that the FK alone permits (the FK only proves the target EXISTS).
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_superseded_forward_ck"
  CHECK ("superseded_by_version" IS NULL OR "superseded_by_version" > "version");--> statement-breakpoint

-- (7c) v1 hosts custom fields on MEMBERS ONLY. FR-54, epics.md:108 and §1.7 all name member, claim
-- AND pool — narrowing to one host is a real coverage gap, recorded as a GATED deferral (story D7),
-- not silently absorbed. Claims are additionally guarded by §1.9/§1.13 against exactly this vector.
-- Extending to another host is a one-line ALTER on this constraint plus that host's own fence review.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_host_entity_ck"
  CHECK ("host_entity" IN ('member'));--> statement-breakpoint

-- (7d) `definition` must at least be an object carrying the identity + label + type + tier keys the
-- readers dereference, with `definition ->> 'field_key'` agreeing with the COLUMN. The column and the
-- body disagreeing would break the version pin outright: the pin is on the column, every reader keys
-- on the body, and nothing else would notice. Per-field interior validation stays an app-layer
-- concern (`validateCustomFieldDefinition`) — a CHECK deep enough for that would be a rule engine.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_definition_shape_ck"
  CHECK (
    jsonb_typeof("definition") = 'object'
    AND "definition" ->> 'field_key' = "field_key"
    AND jsonb_typeof("definition" -> 'label_en') = 'string'
    AND jsonb_typeof("definition" -> 'label_hi') = 'string'
    AND btrim("definition" ->> 'label_en') <> ''
    AND btrim("definition" ->> 'label_hi') <> ''
    AND jsonb_typeof("definition" -> 'field_type') = 'string'
    AND jsonb_typeof("definition" -> 'pii_tier') = 'number'
  );--> statement-breakpoint

-- (7e) v1 accepts pii_tier 3 ONLY (AC4). The app layer raises a typed
-- CustomFieldPiiTierUnsupportedError naming the deferral; this is the mirror for any writer that
-- never reaches it. ⚠ This is a DEFERRAL, not a judgement: Tier-1 needs per-value envelope encryption
-- and Tier-2 needs a blind-index host column, and a shared JSONB column on the certified PII-free
-- `members` table can host neither. When that substrate lands, this constraint widens with it.
-- ⭐ [Review][Patch] A `CASE` guard, not a bare cast: Postgres does NOT guarantee AND/OR short-circuit
-- evaluation order (only CASE does), so `jsonb_typeof(...) = 'number' AND (...)::int = 3` is not a safe
-- way to avoid this. Without the guard, a direct/bypassing INSERT (exactly this CHECK's threat model —
-- a caller that skips the app-layer validator) supplying a non-numeric `pii_tier` (a string, bool,
-- array, or null) risks an opaque `invalid input syntax for type integer` runtime error instead of a
-- clean, named constraint violation. ⚠ `::numeric`, not `::int`: `..._definition_shape_ck` (above)
-- already proves `pii_tier` is a JSON NUMBER, but a JSON number is not necessarily a clean INTEGER
-- literal — `3.5` is a valid JSON number that `'3.5'::int` still raises the same opaque cast error on.
-- `::numeric` accepts any JSON number text (including decimals) and simply compares unequal to 3.
ALTER TABLE "pariwar_custom_field_definitions"
  ADD CONSTRAINT "pariwar_custom_field_definitions_pii_tier_ck"
  CHECK (
    CASE
      WHEN jsonb_typeof("definition" -> 'pii_tier') = 'number' THEN ("definition" ->> 'pii_tier')::numeric = 3
      ELSE false
    END
  );--> statement-breakpoint

-- (3) The three tenant-isolation policies (from policies/pariwar-custom-field-definitions-rls.ts).
-- No DELETE policy and no DELETE grant — see the header.
CREATE POLICY "pariwar_custom_field_definitions_tenant_isolation_select" ON "pariwar_custom_field_definitions" AS PERMISSIVE FOR SELECT TO "twt_app" USING (pariwar_id = nullif(current_setting('app.pariwar_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "pariwar_custom_field_definitions_tenant_isolation_insert" ON "pariwar_custom_field_definitions" AS PERMISSIVE FOR INSERT TO "twt_app" WITH CHECK (pariwar_id = nullif(current_setting('app.pariwar_id', true), '')::uuid);--> statement-breakpoint
CREATE POLICY "pariwar_custom_field_definitions_tenant_isolation_update" ON "pariwar_custom_field_definitions" AS PERMISSIVE FOR UPDATE TO "twt_app" USING (pariwar_id = nullif(current_setting('app.pariwar_id', true), '')::uuid) WITH CHECK (pariwar_id = nullif(current_setting('app.pariwar_id', true), '')::uuid);--> statement-breakpoint

-- (4) The append-only trigger — the clause_versions / routing-policy immutability posture. A version
-- row is INSERT-only; the SOLE legitimately-mutable column on an existing row is
-- superseded_by_version (the forward-pointer). Any other column changing on an UPDATE is rejected.
--
-- ⚠ THIS TRIGGER ENUMERATES ITS COLUMNS EXPLICITLY. A column added to this table LATER is OUTSIDE the
-- append-only guarantee until it is added here too — the same footgun 0089 hit on
-- feature_flag_versions.actor_display. If you ALTER TABLE … ADD COLUMN, come back here.
CREATE FUNCTION pariwar_custom_field_definitions_reject_mutation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.pariwar_id IS DISTINCT FROM OLD.pariwar_id
     OR NEW.host_entity IS DISTINCT FROM OLD.host_entity
     OR NEW.field_key IS DISTINCT FROM OLD.field_key
     OR NEW.version IS DISTINCT FROM OLD.version
     OR NEW.definition IS DISTINCT FROM OLD.definition
     OR NEW.effective_at IS DISTINCT FROM OLD.effective_at
     OR NEW.retired_at IS DISTINCT FROM OLD.retired_at
     OR NEW.authored_by_actor IS DISTINCT FROM OLD.authored_by_actor
     OR NEW.actor_display IS DISTINCT FROM OLD.actor_display
     OR NEW.audit_id IS DISTINCT FROM OLD.audit_id
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION
      'pariwar_custom_field_definitions immutable-column write rejected — only superseded_by_version may be updated on an existing version row (Story 10.12 AC1, the clause_versions posture); attempted a change to pariwar_id/host_entity/field_key/version/definition/effective_at/retired_at/authored_by_actor/actor_display/audit_id/created_at on field "%" version % for pariwar %',
      OLD.field_key, OLD.version, OLD.pariwar_id
      USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER pariwar_custom_field_definitions_immutability_guard
  BEFORE UPDATE ON pariwar_custom_field_definitions
  FOR EACH ROW EXECUTE FUNCTION pariwar_custom_field_definitions_reject_mutation();
